version: '3'
services:
  app:
    build: ./server
    restart: always
    container_name: fademy_app
    ports:
      - "3105:3105"
    networks:
      - fademy_net
    volumes:
      - "./server/:/app/"
      - "./server/ormconfig.docker.json:/app/ormconfig.json"
      - "/app/node_modules"

networks:
  fademy_net:
    external: true